Got a 500 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=KxG5sD5DNZMcK1N3uxoBJYTVGNVAvaARt593U0kUvDHXYWZvrMDRzbCN69928M3c: 500 Error: Failed to establish a backside connection
Got a 500 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=KxG5sD5DNZMcK1N3uxoBJYTVGNVAvaARt593U0kUvDHXYWZvrMDRzbCN69928M3c: 500 Error: Failed to establish a backside connection
Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=KxG5sD5DNZMcK1N3uxoBJYTVGNVAvaARt593U0kUvDHXYWZvrMDRzbCN69928M3c: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}}
Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=KxG5sD5DNZMcK1N3uxoBJYTVGNVAvaARt593U0kUvDHXYWZvrMDRzbCN69928M3c: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}}
Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=KxG5sD5DNZMcK1N3uxoBJYTVGNVAvaARt593U0kUvDHXYWZvrMDRzbCN69928M3c: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}}
Traceback (most recent call last):
  File "/home/sesmart/3_vqa/hqca/tools/Optimizers.py", line 164, in next_step
    self.opt.next_step()
  File "/home/sesmart/3_vqa/hqca/tools/Optimizers.py", line 448, in next_step
    self.R_f = function_call(self.R_x,**self.kwargs)
  File "/home/sesmart/3_vqa/hqca/tools/Optimizers.py", line 69, in function_call
    E_t = En.energy_eval_qc(**kwargs)
  File "/home/sesmart/3_vqa/hqca/tools/Energy.py", line 304, in energy_eval_qc
    **kwargs
  File "/home/sesmart/3_vqa/hqca/tools/QuantumFramework.py", line 68, in evaluate
    **kwargs
  File "/home/sesmart/3_vqa/hqca/tools/QuantumTomography.py", line 258, in add_data
    QuantTomoInst.counts[circuit]
KeyError: 'ii0'
